### PR TITLE
Update prizes 2

### PR DESCRIPTION
**Pull request by MTG2000**
- fix the double border issue
- change $ position
- make sure that prize name remains on one line

### CODE REVIEW

**Comment by MTG2000** [comment]
@johnsBeharry 
why are the checks failing here ??
I opened the logs, but they are not showing anything

P.S: the reason I opened a new PR, is because my commits were not showing on the previous PR (47) for some reason

**Comment by MTG2000** [comment]
I know it sounds weird, but it seems that something is wrong with Github. I've been getting a bunch of 500 error pages randomly, and on the netlify errors log it is saying: "Error checking out repo."

**Comment by johnsBeharry** [comment]
ye I noticed, I was trying to respond to this PR earlier and I couldn't post a comment. deploys are also failing. hopefully it settles soon, also - this is why we need other options than these centralised services

**Comment by MTG2000** [comment]
I'm closing this PR because it seems that netlify can't deploy it.
But instead use the PR 52

**Pull request closed without merging**
